name: Build

on:
    workflow_dispatch: {}

    push:
        branches:
            - main

    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
    contents: read

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7.0.0

            - name: Setup Go
              uses: actions/setup-go@v6.5.0
              with:
                  go-version-file: ./go.mod
                  cache: true

            - name: Verify Modules
              run: go mod verify

            - name: Vet
              run: go vet ./...

            - name: Build
              run: make build

            - name: Build Examples
              run: make build-examples
