name: lint

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  cache: true
                  go-version-file: 'go.mod'

            - uses: golangci/golangci-lint-action@v6
              with:
                  version: v1.59
