name: test

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  cache: true
                  go-version-file: 'go.mod'

            - run: go mod verify

            - run: make test
